### ISSUE TITLE
policy issue when used with tf.exe even after copying the dll to the tf.exe location.

### ISSUE THREAD

**Issue by kriskoneru** [colindembovsky/ColinsALMCornerCheckinPolicies#16] opened 2017-11-15 19:50 UTC
Hello,
this is in continuation about my previous issue. as you have told i have placed "ColinsALMCheckinPolicies.dll" in  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE but still i get the same error as before. 

Please see the screen shots. You can replicate on your local as well. 

this is a production issue that we are facing. 

![checkin-policy](https://user-images.githubusercontent.com/16949860/32856901-2b036266-ca14-11e7-9ea3-1b67221d8791.png)
![checkin-policy-dll-location](https://user-images.githubusercontent.com/16949860/32856902-2b1594f4-ca14-11e7-8596-a4045e207eb5.PNG)

**Comment by colindembovsky** [comment] 2017-11-15 20:41
Duplicate of #15

**Comment by colindembovsky** [comment] 2017-11-15 20:43
I'm asking the VSTS Team what they suggest. Can you double check that the versions are the same (that you're using tf.exe for VS 2015 - that seems to be the version of the extension that you're using).

**Comment by lenahendricks** [comment] 2017-11-15 20:52
Colin, the version of TF.exe is 14.102.25619.0

**Comment by kriskoneru** [comment] 2017-12-06 17:11
hello @colindembovsky any update on the issue.

**Comment by colindembovsky** [comment] 2018-01-02 02:12
@kriskoneru No updates. I'm not sure what to suggest...

**Closed as completed** 2019-03-11 15:46 UTC
